### ISSUE TITLE
UPDATE TODO 정리

### ISSUE THREAD

**Issue by Tao-Kim** [Tao-Kim/worry-and-choice#7]
- [ ] viewModel di처리, 통합
- [ ] paging 처리
- [ ] 알림보기 기능 구현
- [ ] 코드 다듬기.............
- [ ] 자동 로그인 기능
- [ ] 로그아웃 기능
- [ ] 회원탈퇴 기능
- [ ] 메뉴 ui 변경
- [ ] sns 로그인 기능
- [ ] 사용자 선택시 작성자 cloudfunction fcm 푸쉬 - 내 글 선택이 추가됬어요
- [ ] 작성자 선택시, 선택자들에게 cloudfunction fcm 푸시 - 선택한 고민  글쓴이가 결정했어요
- [ ] 댓글 작성시 글 작성자 cloudfunction fcm 푸시 - 내 글 댓글이 달렸어요
- [ ] 대댓글 기능
